### ISSUE TITLE
Embroidery ticket requires both fields to have numbers

### ISSUE THREAD

**Issue by FabosaurusRex** [UTA-FabLab/fabapp#10]
Ending an embroidery ticket requires there be a number in both fields, if not an error message is thrown stating "Material status cannot be used with a 0 quantity for Thread" 

This report assumes material status of Used has been selected.

- if a ticket's duration is less than an hour, the blank hours field should either be pre-filled in with a 0, or assume the null value means 0.

**Comment by MickPoletti** [comment]
The issue has been tentatively fixed, assuming nothing weird happens when I'm not looking, the issue was caused by a repeated division operation in the return statement for the function. This change can be seen in commit #7d8c9ea on branch Bugfix-#11.

**Comment by MickPoletti** [comment]
The issue has been tentatively fixed, after speaking with Eric we came up with some additional changes to make in the bugfix as listed in the latest commit and below in this comment.

- Users should not be able to add materials to thread and embroidery tickets, so remove this for these.
- Round quantity in ticket info modal.
- Remove the ability to add negative numbers in hours and minutes.
- Cancelled ticket status should change thread select status to "not used".

**Comment by FabosaurusRex** [comment]
Verified fix, changed label accordingly.

**Comment by FabosaurusRex** [comment]
Passed testing on dev server.

**Comment by FabosaurusRex** [comment]
Passed testing on Test, currently rolled into Production.  Closing issue.
