### ISSUE TITLE
Bugged quantity with ending embroidery tickets

### ISSUE THREAD

**Issue by FabosaurusRex** [UTA-FabLab/fabapp#11]
When ending an embroidery ticket:

End status of Complete is used
Null value in the Hours field and any numerical value in the Minutes field
Material status of "Not Used" selected
No split materials

The end ticket balance sheet comes up displaying Quantity of "NaN", and a Cost of $0

Ideally this should be prevented one way or another - a Complete status precludes having not used anything, otherwise it would be a Cancel or one of the two Failure types.

**Comment by FabosaurusRex** [comment]
Partially fixed - numbers used in the Hours field are calculated correctly, number used in the Minutes field are incorrect, i.e. 1 hour 30 minutes is billed as 1.0833333333.... units and a cost of $1.01.

**Comment by MickPoletti** [comment]
The issue has been tentatively fixed, assuming nothing weird happens when I'm not looking, the issue was caused by a repeated division operation in the return statement for the function. This change can be seen in commit #7d8c9ea on branch #11

**Comment by FabosaurusRex** [comment]
Clears testing on Dev server.

**Comment by FabosaurusRex** [comment]
Passed testing on Test, is currently rolled into Production.  Closing issue.
