### ISSUE TITLE
Error when adding items to inventory

### ISSUE THREAD

**Issue by FabosaurusRex** [UTA-FabLab/fabapp#16]
When adding a new item to inventory, modal with contents "Update Inventory" header and "undefined" in body appears.  After Update Inventory button is clicked, it gives a confirmation message but item has not actually been added to inventory.

**Comment by FabosaurusRex** [comment]
Found 4 variables being fed when calling populate_modal(), also some possible mis-calls when generating modal body content off of submitted data.

**Comment by MPZinke** [comment]
Issue fixed on branch inventory_repair.  Currently awaiting dev-testing.

**Comment by FabosaurusRex** [comment]
Tested out, issue is fixed.  Discovered some rounding display issues with prices that are < $.01/unit, but that is not part of this issue.

**Comment by FabosaurusRex** [comment]
Everything is good on Dev server testing.

**Comment by FabosaurusRex** [comment]
Passed testing on Test, rolled in to Production.  Closing issue.
