### ISSUE TITLE
Transaction/Wait Tickets do not print

### ISSUE THREAD

**Issue by FabosaurusRex** [UTA-FabLab/fabapp#18]
When a wait ticket is generated, the physical printout does not occur.  No Fabapp users can reprint ticket successfully, button is clicked but no errors or feedback occurs.

**Comment by DeviousFusion** [comment]
This bug also occurs when starting a new transaction from OctoPuppet.

**Comment by DeviousFusion** [comment]
Fixed in: https://github.com/UTA-FabLab/fabapp/commit/27046c4568d2c225fb5fb556d076778af339858d

**Comment by FabosaurusRex** [comment]
Tested reprinting an existing ticket, PHP then broke page.  Retrieved from error log:  

[Tue Jun 23 13:29:32.921305 2020] [proxy_fcgi:error] [pid 9055] [client 129.107.72.175:58493] AH01071: Got error 'PHP message: PHP Notice:  A non well formed numeric value encountered in /opt/www/fabapp-dev.uta.edu/pages/lookup.php on line 473\n', referer: https://fabapp-dev.uta.edu/index.php


[Tue Jun 23 13:29:38.875010 2020] [proxy_fcgi:error] [pid 16843] [client 129.107.72.175:58496] AH01071: Got error 'PHP message: PHP Notice:  A non well formed numeric value encountered in /opt/www/fabapp-dev.uta.edu/pages/lookup.php on line 473\n', referer: https://fabapp-dev.uta.edu/pages/lookup.php?trans_id=45510


[Tue Jun 23 13:30:55.794274 2020] [proxy_fcgi:error] [pid 16843] [client 129.107.72.175:61754] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'Mike42\\Escpos\\InvalidArgumentException' not found in /opt/www/fabapp-dev.uta.edu/api/php_printer/src/Mike42/Escpos/EscposImage.php:456\nStack trace:\n#0 /opt/www/fabapp-dev.uta.edu/class/Transactions.php(293): Mike42\\Escpos\\EscposImage::load('/opt/www/fabapp...', 0)\n#1 /opt/www/fabapp-dev.uta.edu/pages/lookup.php(69): Transactions::printTicket('45510')\n#2 {main}\n  thrown in /opt/www/fabapp-dev.uta.edu/api/php_printer/src/Mike42/Escpos/EscposImage.php on line 456\n', referer: https://fabapp-dev.uta.edu/pages/lookup.php?trans_id=45510

**Comment by FabosaurusRex** [comment]
Tested by starting a print on the dev Pi, print did not occur.  Error log shows same problem:

[Tue Jun 23 13:41:00.943831 2020] [proxy_fcgi:error] [pid 16846] [client 129.107.76.69:41450] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'Mike42\\Escpos\\InvalidArgumentException' not found in /opt/www/fabapp-dev.uta.edu/api/php_printer/src/Mike42/Escpos/EscposImage.php:456\nStack trace:\n#0 /opt/www/fabapp-dev.uta.edu/class/Transactions.php(293): Mike42\\Escpos\\EscposImage::load('/opt/www/fabapp...', 0)\n#1 /opt/www/fabapp-dev.uta.edu/api/flud.php(237): Transactions::printTicket(45511)\n#2 /opt/www/fabapp-dev.uta.edu/api/flud.php(79): PrintTransaction('1000916886', '0026')\n#3 {main}\n  thrown in /opt/www/fabapp-dev.uta.edu/api/php_printer/src/Mike42/Escpos/EscposImage.php on line 456\n'

**Comment by FabosaurusRex** [comment]
Missing dependencies on server(s):  php7.2-gd php7.2-intl and imagemagick are missing.

Emailed Glenn to get them reinstalled.

**Comment by FabosaurusRex** [comment]
Dependencies were reinstalled, tested out, was able to initiate prints via Dev Pi and by printing from Ticket Details page.

Have not tested out a multi-material print yet.

**Comment by FabosaurusRex** [comment]
Tested out with multi-materials ticket, worked correctly.

**Comment by FabosaurusRex** [comment]
Correction to above comment - ticket prints out, but it is not the special color-swap ticket that printed out beforehand.  Just a standard print job ticket.

**Comment by FabosaurusRex** [comment]
Printing is now broken again.  Something in the dev merges broke it.

**Comment by FabosaurusRex** [comment]
This appears to not actually have been merged in, only tags were altered.

**Comment by FabosaurusRex** [comment]
Confirmed as working on dev now.

**Comment by FabosaurusRex** [comment]
Passed tests in Test and is now rolled into Production.  Closing issue.
