### ISSUE TITLE
PHP 7 Compatibility

### ISSUE THREAD

**Issue by FabosaurusRex** [UTA-FabLab/fabapp#19]
Web cluster is being updated to PHP7 at the end of march, tentatively.  

FabApp needs to be fully PHP 7 compatible.

**Comment by DeviousFusion** [comment]
Duplicate issue: #4 
Possible fix: #5

**Comment by FabosaurusRex** [comment]
Fix is live, everything appears to be working correctly so far.  Closing issue.
