### ISSUE TITLE
Picking up items from storage produces error message

### ISSUE THREAD

**Issue by FabosaurusRex** [UTA-FabLab/fabapp#27]
When a print job finishes and is placed in storage, subsequent attempts to end the ticket, remove the item, and end the ticket produces:

Missing location for item during ending modal
Clicking submit to go to billing page results in "Ticket XXX already ended" modal

**Comment by FabosaurusRex** [comment]
Going through the End Ticket functionality for #47473 on test:

Ended ticket > directed to End Ticket page, filled out weight and end status of "Pickup" > clicked "End" button, clicked "Submit" on modal > Redirected to payment page.

Selected IDT on Payment dropdown list, then clicked off to the home page. Ticket is no longer open on printer, looking up ticket by number shows a status of "Complete" with no account stipulated.

**Comment by MPZinke** [comment]
Ready for dev-testing.  Git logs note changes in code: functions, logic, commenting.
Also fixes Bug #8

**Comment by FabosaurusRex** [comment]
Stored-then-picked-up aspect of bug is mostly fixed, however:  at the payment page(pay.php) I fill in the operator correctly, set the Payment dropdown CS Gold, click Launch CS Gold button, and get the CS Gold login page and the modal stating "Did you take payment, did you log out of CS Gold".  Payment page is closed, then the OK button on the modal is clicked. The "Launch CS Gold" button changes to "Confirm Payment" immediately, and then the page redirects to the Ticket Details page(lookup.php) for the transaction, with a modal indicating the ticket is complete which closes automatically after a second or two.  User is not able to utilize the Confirm Payment button to actually confirm the payment occured successfully.

**Comment by FabosaurusRex** [comment]
Tested out direct pick-up, no issues with any of the accounts other than CS Gold - behavior is identical when selecting CS Gold as account.

**Comment by FabosaurusRex** [comment]
Loaded full code from this bugfix branch onto fabapp, created new ticket through Dev Pi, tested out - still unable to utilize the Confirm Payment button after clicking the "OK" in "Did you take payment?  Did you log out of CS Gold?" modal.  User still unable to utilize the Confirm Payment button.

**Comment by FabosaurusRex** [comment]
Incorrect pay page logic is confirmed as a Firefox-specific issue.

**Comment by FabosaurusRex** [comment]
Pay page logic bug will be treated as a seperate issue, this one is ready for merge into Dev branch.

**Comment by FabosaurusRex** [comment]
Reloaded dev branch onto Dev server, tested, confirmed working properly.  Loading onto Test server next.

**Comment by FabosaurusRex** [comment]
Confirmed fixed on Test server.  Marking appropriately.

**Comment by FabosaurusRex** [comment]
Scheduled to go live 6/22.

**Comment by FabosaurusRex** [comment]
Confirmed fixed in production.  Closing issue.
