### ISSUE TITLE
Offline Mode: Invalid server response when uploading offline transactions

### ISSUE THREAD

**Issue by DeviousFusion** [UTA-FabLab/fabapp#35]
Its a commit derp:

Original commit: https://github.com/UTA-FabLab/fabapp/commit/1829625a0d34a88f79bcd75df5cb291f8c01a6c6
Overwriiten by: https://github.com/UTA-FabLab/fabapp/commit/e45d6768c22b7b00d9a9de74df0240f7a16f3669#diff-61f2a7d49b29bc463db78b03a67d5dbb

**Comment by DeviousFusion** [comment]
Status:

- [x] Create offline_transactions table
- [x] flud: Add logic to differetitate between offline and online transactions
- [x] Transactions: Update required tables
- [x] flud: Update end ticket time

**Comment by FabosaurusRex** [comment]
Any progress on this?  It's 72 commits behind, we will need to watch out that we don't commit old code on top of new code by accident(again).

**Comment by DeviousFusion** [comment]
Not inline with dev, but it works now. Now uses the existing transaction processing methods but relies on transaction number retrieved from offline_transaction table.
Todo:
- [x] Update index ui
- [x] Create printTicket stuff
- [x] Lookup Transactions - Offline
- [x] Keep offline link visible
- [x] Re-add offline id to lookup page

**Comment by DeviousFusion** [comment]
Branch is now inline with dev

**Comment by FabosaurusRex** [comment]
Tested out, everything appears to be working properly on the FA side of things.  Approved to merge into Dev.

**Comment by FabosaurusRex** [comment]
Fix has been rolled out to production.  Closing issue.
