### ISSUE TITLE
Any failed ticket requires at least 1 failed material

### ISSUE THREAD

**Issue by surbhiz** [UTA-FabLab/fabapp#36]
While ending the transaction for JuiceBox and selecting the 'Partial fail' or 'Total fail' from the drop down menu on the Web UI, it pops up an error on line 55 of pages/end.php 
`undefined property::$device_group 'if($ticket->no_associated_materials_have_a_price() && $ticket->device_group->is_select_mats_first)'`

**Comment by FabosaurusRex** [comment]
Discussed options, will limit options for ending ticket for all Juicebox-managed items to Complete and Cancelled.

**Comment by FabosaurusRex** [comment]
Needs to be fixed and ready for testing by Oct. 12.

**Comment by FabosaurusRex** [comment]
I don't really know what i'm doing here, adding Mathew on for assistance/reference on this.

**Comment by MPZinke** [comment]
Updated with Bugfix-#36 branch.  `$ticket->device_group->is_select_mats_first` was changed missing attribute [Devices object] device call.  It has been changed to `$ticket->device->device_group->is_select_mats_first` to make the right object(s) call.

**Comment by FabosaurusRex** [comment]
Juicebox devices still getting Total Fail and Partial Fail as possible end statuses.  Need to be limited to Complete or Cancelled as discussed earlier in the year.

**Comment by MPZinke** [comment]
As par 
> Discussed options, will limit options for ending ticket for all Juicebox-managed items to Complete and Cancelled.
Juicebox Managed tickets only have statuses Complete and Cancelled.
Changes pushed to branch `Bugfix-#36` and are ready for testing

**Comment by FabosaurusRex** [comment]
Passed initial Dev testing, marking approved for merge into Dev.

**Comment by FabosaurusRex** [comment]
Fix has been rolled out to production.  Closing issue.
