### ISSUE TITLE
Feature Request - Modification for wait queue text content

### ISSUE THREAD

**Issue by FabosaurusRex** [UTA-FabLab/fabapp#37]
Wait queue notifications currently have the text hard-coded in - notification text should be transitioned to be retrieved from  configurable site variables instead.  Each discrete notification message should have its own variable to pull from.

**Comment by MickPoletti** [comment]
Added new site variables to local DB and uploaded table SQL to teams under /FabApp Code Documentation/Current/Site Variables Update. Made changes in wait_ticket.php to handle these additions and display alert text customizable from DB.

**Comment by FabosaurusRex** [comment]
For clarity's sake:  

All messages that will be texted/emailed to the users in queue should be transitioned to pull from editable site variables.

**Comment by FabosaurusRex** [comment]
Discovered the date+time is not sending when manual alerts are being sent.  Piggybacking this bug onto the feature request.

Also discovered that selecting the Project Fi option results in no SMS being sent successfully.  Piggybacking this on as well.

**Comment by FabosaurusRex** [comment]
Fi has some issue where the gateway won't accept our messages but everyone else will.  

Tried switching up the name and domain for the sender, did not work, so we're putting fixing Fi messaging on hold for now.

Google may have put us on a deny list or something.

**Comment by MickPoletti** [comment]
I updated the Wait  Queue class file to interface with the changes made in site variables and to use those instead of hardcoded values. The updated table can be found on teams in FabApp Code Documentation/FabAppV0.96.1 (site_variables.sql)

**Comment by MickPoletti** [comment]
Looks like there were conflicts between the $msg variable on index.php and wait_ticket.php that were causing issues with the messages being sent to users. After a not-insignificant amount of time, Eric and I were able to track this down. Hopefully, that issue is now fixed.

**Comment by FabosaurusRex** [comment]
Turns out you can't put single quotes in the contents of the variables as they are currently handled too.

**Comment by FabosaurusRex** [comment]
Seeing as how we've exhaustively tested this for a couple hours trying to figure out the issue, i am approving this to merge into dev.

The intolerance for special characters will be dealt with in another issue/branch in the interests of delivering the MVP on 7/27.

**Comment by MickPoletti** [comment]
Merged into dev

**Comment by FabosaurusRex** [comment]
Timers don't work with wait queue tickets created after reloading the dev branch.  Send Manual Message starts the 5 minute timer successfully, and continues counting past 0 and into negative numbers successfully.

edit:  scratch that, i'm dumb, machines are listing properly.

**Comment by FabosaurusRex** [comment]
With 2 wait tickets of the same operator ID:  Creating a new ticket for vinyl through the Process Ticket dropdown brings up Create New Ticket page for Roland, but submitting new ticket produces the error message "Can not create a new ticket–WQ Error 220 : Unstable Query Result".  This does not happen for the Polyprinter queue.

Deleted one of the tickets and retried, was able to successfully create a vinyl ticket again.  Having 2 tickets again causes the problem to reoccur - relevant SQL query may need to have the results ordered in order to function properly.

**Comment by FabosaurusRex** [comment]
2 entries of the same ID in the Polyprinter wait queue cause it to no longer remove existing wait tickets in the polyprinter queue when one is processed.

**Comment by FabosaurusRex** [comment]
Wait queue issue behaviors appear to not have been caused by customizing the wait queue messages.

They appear to be caused by ambiguous SQL queries that are now able to return multiple results due to enabling multiple tickets per queue for the same 1000#, which was disallowed from happening before.

**Comment by FabosaurusRex** [comment]
Work on this is shifting to Issue #38 now.

**Comment by FabosaurusRex** [comment]
Closing issue.
