### ISSUE TITLE
Non-employee users cannot cancel their own wait list tickets

### ISSUE THREAD

**Issue by FabosaurusRex** [UTA-FabLab/fabapp#38]
Previously, all users had the ability to log in to fabapp and self-cancel any wait tickets they currently had.  At some point, that stopped working and we need to bring it back.

Self-cancellation of wait list tickets is a big facet of the fall semester workflow so we need this resolved relatively quickly.

**Comment by MPZinke** [comment]
Added two methods to Wait_queue class to get tickets for operator and check if wait_queue ticket belongs to a specific user.  pages/info.php now has code to display and cancel wait queue tickets for logged in user.  
Development for this is now complete and ready for testing.

**Comment by FabosaurusRex** [comment]
Enabled multiple wait tickets per machine queue.  Will be doing testing Monday.

**Comment by FabosaurusRex** [comment]
Tested, appears to be working correctly.  Approved to merge into Dev branch.

**Comment by FabosaurusRex** [comment]
Comments/commits on the wait queue issues recently revealed are continuing on this branch now.

**Comment by MPZinke** [comment]
Multiple wait_queue tickets for a device or device group produces an ambiguous query.  Ready for dev testing.

**Comment by FabosaurusRex** [comment]
appears to pass tests correctly on Dev server.

**Comment by FabosaurusRex** [comment]
Passed testing on Test, currently rolled into Production.  Closing issue.
