### ISSUE TITLE
Error in PHP 7 - Class Error in file Error.php causes php to give fatal error.

### ISSUE THREAD

**Issue by MickPoletti** [UTA-FabLab/fabapp#4]
Error is a built in class in PHP 7, so maybe rename the class, or put it in a namespace to avoid conflict.
https://stackoverflow.com/questions/52301800/fatal-error-cannot-declare-class-error-because-the-name-is-already-in-use

**Comment by DeviousFusion** [comment]
Thanks for submitting this. We are working on transitioning to PHP7. I am closing this issue and continue bug tracking on issue #19
