### ISSUE TITLE
Pickup total fail tickets do not remove from storage

### ISSUE THREAD

**Issue by MPZinke** [UTA-FabLab/fabapp#42]
If a ticket is put into storage, then picked up and marked as total fail, it does not remove the object from storage.  
This is overlooked because all other ticket statuses proceed to ~/pages/pay.php where it is removed.
This can be fixed by adding a removal call in the if statement https://github.com/UTA-FabLab/fabapp/blob/bd1b5eed5575a92f922e72b25172f9bced09c76e/pages/pickup.php#L65

**Comment by FabosaurusRex** [comment]
@MickPoletti , you broke the UI.  Fix please.

**Comment by MPZinke** [comment]
Additional pickup process issue found while looking into this.  There is a foreach statement [here](https://github.com/UTA-FabLab/fabapp/blob/bd1b5eed5575a92f922e72b25172f9bced09c76e/pages/end.php#L270l) that causes the materials for each device to echo the "additional device" device option.

**Comment by MPZinke** [comment]
~/pages/pickup.php now removes object from storage_box if ticket is marked as total fail.  This is because the object will be thrown in the trash or recycling.

**Comment by MickPoletti** [comment]
I removed the foreach statement that Mathew pointed out and it seems to have fixed the UI issue.

**Comment by FabosaurusRex** [comment]
UI issue appears to be fixed.

Tested out object removal - objects are still remaining in storage when ticket is ended as a Total Failure.

**Comment by MPZinke** [comment]
Bug fixed and ready for testing.  Added correct variable name to fix issue.

**Comment by FabosaurusRex** [comment]
Passes tests in Dev branch on dev server.

**Comment by FabosaurusRex** [comment]
At some point Friday, the Information page stopped working and is now either calling incorrect index values and/or calling something that doesn't exist.  This is top priority to get it working again and figure out what happened.

**Comment by FabosaurusRex** [comment]
Issue was fixed, has been tested, and is currently rolled in to Production branch.  Closing.
