### ISSUE TITLE
Ending the transaction returns success but t_end not updating in the Database

### ISSUE THREAD

**Issue by surbhiz** [UTA-FabLab/fabapp#45]
While ending the transaction for JuiceBox, json returns `{"CONTENT":"Ticket 45744 has been closed","success":"Y"}` which indicates that the code is running fine but in Database it returns the t_end as NULL which signifies that it is not updating the value for the end ticket.

```
trans_id | d_id | operator | est_time | t_start | **t_end**
45744 | 48 | 1001763409 | NULL | 2020-07-23 15:10:27 | **NULL**
```

**Comment by FabosaurusRex** [comment]
Forgot to update this - the evaluation logic on line 272 of juicebox.php needed to be amended to check for a null status rather than a True status. Once updated, it began working correctly.

**Comment by FabosaurusRex** [comment]
This has been live, waiting for confirmation that the issue is resolved after going live on the Production server.

**Comment by FabosaurusRex** [comment]
Confirmed working on Production.  Closing issue.
