### ISSUE TITLE
Project Fi SMS updates do not go through

### ISSUE THREAD

**Issue by FabosaurusRex** [UTA-FabLab/fabapp#50]
Fi has stopped accepting SMS updates from FabApp.

Need to add full set of headers in and troubleshoot problem:
https://stackoverflow.com/questions/566182/complete-mail-header

I can SMS myself from my @uta.edu address successfully, so the domain is likely not blocked.

**Comment by FabosaurusRex** [comment]
Testing proves it's something wrong in the DB query - changing Project Fi to Project_Fi produced a successful message.

**Comment by FabosaurusRex** [comment]
Retyped the MMS server address as well in case of hidden characters being an issue from copy/pasting from non-plaintext documents in the past.

**Comment by FabosaurusRex** [comment]
Changed Project_Fi back to Project Fi, retried, confirmed it's the space that is breaking things.

**Comment by MPZinke** [comment]
Found issue with font end syntax [here](https://github.com/UTA-FabLab/fabapp/blob/87a9cba38fb52e06496bdcf2e466ab2e1ac50f22/pages/wait_ticket.php#L154). This can be corrected by adding single quotes around the value of the provider.

**Comment by FabosaurusRex** [comment]
Confirmed fix.  Approved to make this change and commit directly to Dev branch.

**Comment by FabosaurusRex** [comment]
Fix has been rolled into Production branch, closing issue.
