### ISSUE TITLE
DB: Update filename location

### ISSUE THREAD

**Issue by DeviousFusion** [UTA-FabLab/fabapp#57]
Filenames are currently being stored in mats_used table. Move this back to transactions table. Possibly helps with #9

**Comment by FabosaurusRex** [comment]
Needs to be fixed and ready for testing by Oct. 12.

**Comment by FabosaurusRex** [comment]
This appears to be the root cause of #9.

**Comment by FabosaurusRex** [comment]
Filename location has been updated to the Transactions notes field from the mats_used notes field.  Closing.
