### ISSUE TITLE
Allow employee to change location when placing item into storage

### ISSUE THREAD

**Issue by FabosaurusRex** [UTA-FabLab/fabapp#8]
Many users are requesting they not be locked into only utilizing the storage location pre-selected by FabApp.

Continue excluding storage locations from use that are marked as being currently occupied, however.

**Comment by FabosaurusRex** [comment]
Tentatively fixed, waiting for review and testing

**Comment by FabosaurusRex** [comment]
Ran into further issue:  when an object's size is selected, changing the drawer number from suggested drawer to a new one causes the size drop-down to go back to null and produces a "Drawer undefined" text instead of "Drawer <1/2/3/etc>"

**Comment by MPZinke** [comment]
Fixed with Bugfix-#27 pickup process. Currently in dev-testing

**Comment by FabosaurusRex** [comment]
Tested after loading up code changes from issue #27 bugfix branch, no change in behavior found. Still displays "Drawer Undefined" when drawer location is manually changed.

**Comment by FabosaurusRex** [comment]
Re-loaded entire #27 bugfix branch and re-tested, Undefined drawer error no longer occurring - appears to be fixed!

**Comment by MPZinke** [comment]
Added JS check in modal population to prevent continuation of process when storage status selected but no location is found.  This happens when end button is clicked and before confirmation modal becomes visible.  If no location is found, storage status is deselected.

**Comment by FabosaurusRex** [comment]
Loaded dev branch back into Dev server and tested, works correctly.  Moving to Test next.

**Comment by FabosaurusRex** [comment]
Confirmed working on Test server.  Changing label appropriately.

**Comment by FabosaurusRex** [comment]
Scheduled to go live 6/22.

**Comment by FabosaurusRex** [comment]
Confirmed fixed, closing issue.
