### ISSUE TITLE
Color swap files do not print out correct ticket

### ISSUE THREAD

**Issue by FabosaurusRex** [UTA-FabLab/fabapp#9]
From Jeffrey:

Any time you use the color swap tool within FabApp, upload the g-code to Octopuppet, and start the print... the ticket that prints out does not say color swap on it or have any directions for the operator to do the color swap. The printer does still pause correctly for the color swap.

**Comment by MickPoletti** [comment]
I think I fixed the issue with this ticket on dev server. Waiting on Vikram to get to the FabLab because there is a massive build-up of receipts making it impossible to verify the fix.

**Comment by FabosaurusRex** [comment]
Needs to be fixed and ready for testing by October 12.

**Comment by FabosaurusRex** [comment]
Requested Mathew incorporate a small fix to the wait queue ticket issuing logic - it has nothing to do with this but was too small(<10 lines) to warrant its own branch.

**Comment by MickPoletti** [comment]
The changes Tushar made may have had an effect on the issue, but for some reason, we're still not getting the filename at https://github.com/UTA-FabLab/fabapp/blob/9ee2c400b55e61ecf9fb358e4ff168d31428baff/class/Transactions.php#L335 . I uncommented the portion that was commented on dev to see if color swap would print at all but at this point, it's still not working. It may be possible that the issue starts right before we hit this line https://github.com/UTA-FabLab/fabapp/blob/production/class/Transactions.php#L307 or somewhere on 335. The last thing I tried was to print out the filename variable to the ticket and see if it printed out on the dev printer. Unfortunately, this did not work and nothing was printed but the filename arguments. At this point, I can't get into the dev server to make changes but my changes should still be in that file. I still believe somewhere on the API side we're still not getting the filename properly.

**Comment by FabosaurusRex** [comment]
#57 is the root cause of this, the filename was never transitioned from being stored in mats_used into transactions inside FLUD.

**Comment by FabosaurusRex** [comment]
@MPZinke posted a possible fix to dev server, the filename stores in the right place when ticket is started on dev pi, but ticket is not printed out automatically.  Manual command to reprint the ticket produces an accurate job ticket with the filename on it, and can be repeated without any issues.

**Comment by FabosaurusRex** [comment]
Filename storage was moved over to transactions table where it was expected to be, multi-material printing works nominally but has formatting errors present.  The multi-material file may not have been generated completely correctly though, the tool stated there was only 1 valid change when 3+ were stipulated.  
![20201008_172050](https://user-images.githubusercontent.com/18125114/95520310-95e7cd00-098c-11eb-8b80-b8527ebbfa22.jpg)
.

**Comment by FabosaurusRex** [comment]
Fixed ticket formatting issues - logic evaluating for how many materials are in the job won't work until Octopuppet is collecting and reporting back all materials instead of just the first, so "Color Swap" won't print out unless we hard-code it to do so right now. 

Marking ready for testing.
![IMG2324135721966927075](https://user-images.githubusercontent.com/18125114/95626338-b1f87680-0a3f-11eb-8860-8a67e307390e.jpg)

**Comment by FabosaurusRex** [comment]
Passed dev server testing, ready to merge in.

**Comment by FabosaurusRex** [comment]
Original #9 branch was hopelessly outdated and based off of who knows what, pull -r commands never brought it up to par with current Production.  In order to avoid another Commit of Doom, made a new branch based off of the Dev branch, titled it Bugfix #9 - RetryMerge.  Placed relevant work into that, committed, then merged new branch in to Dev.

**Comment by FabosaurusRex** [comment]
Fix has been rolled out to production.  Closing issue.
